name: Build and analyze

on:
  workflow_dispatch:
  push:
    branches: [ "*", "**" ]
  pull_request:
    branches: [ master ]
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11 # JDK 11+ required for Sonarcloud to work properly
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      if: github.repository_owner == 'daniel-frak' # Try to disable sonarcloud analysis for forks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: "dfc3a63c86e79fe71dd4dccbd583f36089fd5371"
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -P code-coverage -P sonar-cloud --file pom.xml
    - name: Mutation test
      run: mvn clean test-compile -Ppitest-config -Ppitest-pr -DoriginBranch=${GITHUB_REF#refs/heads/}
    - name: Archive mutation coverage results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: code-coverage-report
        path: target/pit-reports
