name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Setup Git user
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Set POM version to release version
        run: mvn versions:set -DnewVersion=${GITHUB_REF##*/}
      - name: Replace 'since SNAPSHOT' occurrences with 'since ${{ github.ref_name }}'
        uses: mingjun97/file-regex-replace@v1
        with:
          regex: '(?<!`@)since SNAPSHOT(?!`)'
          replacement: 'since ${{ github.ref_name }}'
      - name: Commit changes
        run: |
          git add pom.xml ./\*.java ./\*.md
          git commit -m "Set version to $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - name: Publish package
        run: mvn -B deploy -P release-sign-artifacts
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Increment version
        run: mvn versions:set -DnextSnapshot
      - name: Pull and commit changes
        run: |
          git add pom.xml
          git commit -m "Increment version to $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}